weaviate_version: 0.8.6
markdown: kramdown
kramdown:
    parse_block_html: false
rdiscount extensions: [smart]
sass:
    style: compressed # opposed to "expanded"
    sass_dir: css/_sass
collections:
    blog:
        output: true
        permalink: '/blog/:path'
    use_cases:
        output: true
        permalink: '/use-cases/:path'
    authors:
        output: true
exclude:
    - "*.json"
    - "Gemfile*"
    - "*.enc"
    - vendor
    - README.md
    - "*.draft"
    - js-src
plugins:
    - jekyll-autoprefixer
    - jekyll-redirect-from
whitelist:
    - jekyll-redirect-from
autoprefixer:
    browsers:
        - last 5 versions
