weaviate_version: 0.8.6
markdown: kramdown
kramdown:
    parse_block_html: false
rdiscount extensions: [smart]
collections:
    blog:
        output: true
    authors:
        output: true
exclude:
    - "*.json"
    - "Gemfile*"
    - "*.enc"
    - vendor
    - README.md
    - "*.draft"
    - js-src
    - node_modules
    - webpack.config.js
plugins:
    - jekyll-redirect-from
whitelist:
    - jekyll-redirect-from
